POWER_SPECTRUM := $(patsubst src/power_spectrum/%.cpp,$(HACCGPM_BUILD_DIR)/%.o, $(wildcard src/power_spectrum/*.cpp)) $(patsubst src/power_spectrum/%.cu,$(HACCGPM_BUILD_DIR)/%.o, $(wildcard src/power_spectrum/*.cu))

HACCGPM_FILES += $(POWER_SPECTRUM)
HACCGPM_NOPYTHON_FILES += $(POWER_SPECTRUM)