#PM_SOLVER := $(patsubst src/pm_solver/%.cpp,$(HACCGPM_BUILD_DIR)/%.o, $(wildcard src/pm_solver/*.cpp)) $(patsubst src/pm_solver/%.cu,$(HACCGPM_BUILD_DIR)/%.o, $(wildcard src/pm_solver/*.cu))

HACCGPM_FILES += $(HACCGPM_BUILD_DIR)/greens.o $(HACCGPM_BUILD_DIR)/solver.o $(HACCGPM_BUILD_DIR)/InitGreens.o
HACCGPM_NOPYTHON_FILES += $(HACCGPM_BUILD_DIR)/greens.o $(HACCGPM_BUILD_DIR)/solver.o $(HACCGPM_BUILD_DIR)/InitGreens.o