name: static

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
      runs-on: ubuntu-20.04
      steps:
      - uses: actions/checkout@v2
      - uses: Jimver/cuda-toolkit@v0.2.11
        id: cuda-toolkit
        with:
          cuda: '12.1.0'
          method: 'local'
      - name: make static
        run: source env/bashrc.github.cuda.static; make static